### ISSUE TITLE
Missing tgatool.c file

### ISSUE THREAD

**Issue by gameblabla** [megatron-uk/x68klauncher#1]
Hello,
Here :
https://github.com/megatron-uk/x68klauncher/tree/master/tools

It says something about tgatool.c but the file is nowhere to be found, neither on this repo or elsewhere on the internet.
Perhaps you should add it to this repo ? (or am i missing something ?)

**Comment by megatron-uk** [comment]
That file isn't actually used - it was a piece of sample code for writing tiles to sprite/background ram. It was present in early versions of the repository but was never actually part of the codebase. The readme file needs to be updated to reflect the fact it isn't there any longer.

The original file was referenced in some early discussions when the application was first being developed, over on the GameSX, NFG forums: https://nfggames.com/forum2/index.php?topic=6764.0
